// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skiyknuejsgjnskziqkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNraXlrbnVlanNnam5za3ppcWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzA0OTIsImV4cCI6MjA2Njk0NjQ5Mn0.VZV0rEHpKC6sMPCQ4HH6BKqu8KIgnHfNXq8rLR0O3A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});